const tileState = [
  {
    streetName: '',
    tileType: 'start',
  },
  {
    streetName: 'Parker St.',
    tileType: 'normal',
    color: 'brown',
    price: 60,
    rent: 2,
  },
  {
    streetName: 'Chest',
    tileType: 'chest',
  },
  {
    streetName: 'Tyne St.',
    tileType: 'normal',
    color: 'brown',
    price: 60,
    rent: 4,
  },
  {
    streetName: 'Income Tax',
    tileType: 'expense',
    rent: 200,
  },
  {
    streetName: 'Reading Railroad',
    tileType: 'railroad',
    color: 'railroad',
    price: 200,
  },
  {
    streetName: 'Brighton Vale',
    tileType: 'normal',
    color: 'lightblue',
    price: 100,
    rent: 6,
  },
  {
    streetName: 'Chance',
    tileType: 'chance',
  },
  {
    streetName: 'Granary Vale',
    tileType: 'normal',
    color: 'lightblue',
    price: 100,
    rent: 6,
  },
  {
    streetName: 'Burford Vale',
    tileType: 'normal',
    color: 'lightblue',
    price: 120,
    rent: 8,
  },
  {
    streetName: 'Jail',
    tileType: 'jail',
  },
  {
    streetName: 'Holden Fold',
    tileType: 'normal',
    color: 'pink',
    price: 140,
    rent: 10,
  },
  {
    streetName: 'Electric Company',
    tileType: 'company',
    price: 150,
  },
  {
    streetName: 'Mere Fold',
    tileType: 'normal',
    color: 'pink',
    price: 140,
    rent: 10,
  },
  {
    streetName: 'Hedger Fold',
    tileType: 'normal',
    color: 'pink',
    price: 160,
    rent: 12,
  },
  {
    streetName: 'Pennsylvania Railroad',
    tileType: 'railroad',
    color: 'railroad',
    price: 200,
  },
  {
    streetName: 'Danthorpe Lodge',
    tileType: 'normal',
    color: 'orange',
    price: 180,
    rent: 14,
  },
  {
    streetName: 'Chance',
    tileType: 'chance',
  },
  {
    streetName: 'Rockingham Lodge',
    tileType: 'normal',
    color: 'orange',
    price: 180,
    rent: 14,
  },
  {
    streetName: 'Aveling Lodge',
    tileType: 'normal',
    color: 'orange',
    price: 200,
    rent: 16,
  },
  {
    streetName: '',
    tileType: 'parking',
  },
  {
    streetName: 'Brambleberry Lane',
    tileType: 'normal',
    color: 'red',
    price: 220,
    rent: 18,
  },
  {
    streetName: 'Chance',
    tileType: 'chance',
  },
  {
    streetName: 'Guildford Lane',
    tileType: 'normal',
    color: 'red',
    price: 220,
    rent: 18,
  },
  {
    streetName: 'Albany Lane',
    tileType: 'normal',
    color: 'red',
    price: 240,
    rent: 20,
  },
  {
    streetName: 'Short Line',
    color: 'railroad',
    tileType: 'railroad',
    price: 200,
  },
  {
    streetName: 'Elms Villas',
    tileType: 'normal',
    color: 'yellow',
    price: 260,
    rent: 22,
  },
  {
    streetName: 'Keepers Villas',
    tileType: 'normal',
    color: 'yellow',
    price: 260,
    rent: 22,
  },
  {
    streetName: 'Water Company',
    tileType: 'company',
    price: 150,
  },
  {
    streetName: 'Moorcraft Villas',
    tileType: 'normal',
    color: 'yellow',
    price: 280,
    rent: 24,
  },
  {
    streetName: 'Go to jail',
    tileType: 'gojail',
  },
  {
    streetName: 'Whilworth Gardens',
    tileType: 'normal',
    color: 'green',
    price: 300,
    rent: 26,
  },
  {
    streetName: 'Brock Gardens',
    tileType: 'normal',
    color: 'green',
    price: 300,
    rent: 26,
  },
  {
    streetName: 'Chest',
    tileType: 'chest',
  },
  {
    streetName: 'Fair Gardens',
    tileType: 'normal',
    color: 'green',
    price: 320,
    rent: 28,
  },
  {
    streetName: 'B. & O. Railroad',
    color: 'railroad',
    tileType: 'railroad',
    price: 200,
  },
  {
    streetName: 'Chance',
    tileType: 'chance',
  },
  {
    streetName: 'Hartington Avenue',
    tileType: 'normal',
    color: 'blue',
    price: 350,
    rent: 35,
  },
  {
    streetName: 'Luxury Tax',
    tileType: 'expense',
    rent: 75,
  },
  {
    streetName: 'Meadowlands Avenue',
    tileType: 'normal',
    color: 'blue',
    price: 400,
    rent: 50,
  },
];

module.exports = tileState;
