const backOfCards = [
  {
    cardName: 'Start',
    type: 'Event',
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Parker St.',
    color: 'brown',
    type: 'Property',
    price: 60,
    rent: 2,
    details1: 'With 1 House $10',
    details2: 'With 2 Houses $30',
    details3: 'With 3 House $90',
    details4: 'With 4 Houses $160',
    details5: 'With 5 Houses $250',
    houseCost: 50,
    mortgage: 30,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chest',
    details1: 'Advance to GO, and collect 400. The first player to question you must pay you 100.',
    clicked: false,
  },
  {
    cardName: 'Tyne St.',
    color: 'brown',
    type: 'Property',
    price: 60,
    rent: 4,
    details1: 'With 1 House $20',
    details2: 'With 2 Houses $60',
    details3: 'With 3 House $180',
    details4: 'With 4 Houses $320',
    details5: 'With 5 Houses $450',
    houseCost: 50,
    mortgage: 30,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Income Tax',
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Reading Railroad',
    price: 200,
    details1: 'If 1 owned $25',
    details2: 'If 2 owned $50',
    details3: 'If 3 owned $100',
    details4: 'If 4 owned $200',
    mortgage: 100,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Brighton Vale',
    color: 'lightblue',
    price: 100,
    rent: 6,
    details1: 'With 1 House $30',
    details2: 'With 2 Houses $90',
    details3: 'With 3 House $270',
    details4: 'With 4 Houses $400',
    details5: 'With 5 Houses $550',
    houseCost: 50,
    mortgage: 50,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chance',
    details1: 'You have been elected chairman of the board. Pay each player 50.',
    clicked: false,
  },
  {
    cardName: 'Granary Vale',
    color: 'lightblue',
    price: 100,
    rent: 6,
    details1: 'With 1 House $30',
    details2: 'With 2 Houses $90',
    details3: 'With 3 House $270',
    details4: 'With 4 Houses $400',
    details5: 'With 5 Houses $550',
    houseCost: 50,
    mortgage: 50,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Burford Vale',
    color: 'lightblue',
    price: 120,
    rent: 8,
    details1: 'With 1 House $40',
    details2: 'With 2 Houses $100',
    details3: 'With 3 House $300',
    details4: 'With 4 Houses $450',
    details5: 'With 5 Houses $600',
    houseCost: 50,
    mortgage: 60,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Jail',
    clicked: false,
  },
  {
    cardName: 'Holden Fold',
    color: 'pink',
    price: 140,
    rent: 10,
    details1: 'With 1 House $50',
    details2: 'With 2 Houses $150',
    details3: 'With 3 House $450',
    details4: 'With 4 Houses $625',
    details5: 'With 5 Houses $750',
    houseCost: 100,
    mortgage: 70,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Electric Company',
    details1: 'If 1 owned, rent equals 4 times dice roll.',
    details2: 'If 2 owned, rent equals 10 times dice roll.',
    mortgage: 75,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Mere Fold',
    color: 'pink',
    price: 140,
    rent: 10,
    details1: 'With 1 House $50',
    details2: 'With 2 Houses $150',
    details3: 'With 3 House $450',
    details4: 'With 4 Houses $625',
    details5: 'With 5 Houses $750',
    houseCost: 100,
    mortgage: 70,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Hedger Fold',
    color: 'pink',
    price: 160,
    rent: 12,
    details1: 'With 1 House $60',
    details2: 'With 2 Houses $180',
    details3: 'With 3 House $500',
    details4: 'With 4 Houses $700',
    details5: 'With 5 Houses $900',
    houseCost: 100,
    mortgage: 80,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Pennsylvania Railroad',
    color: 'railroad',
    price: 200,
    details1: 'If 1 owned $25',
    details2: 'If 2 owned $50',
    details3: 'If 3 owned $100',
    details4: 'If 4 owned $200',
    mortgage: 100,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Danthorpe Lodge',
    color: 'orange',
    price: 180,
    rent: 14,
    details1: 'With 1 House $70',
    details2: 'With 2 Houses $200',
    details3: 'With 3 House $550',
    details4: 'With 4 Houses $700',
    details5: 'With 5 Houses $900',
    houseCost: 100,
    mortgage: 90,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Chance',
    details1: 'Go back 3 spaces.',
    clicked: false,
  },
  {
    cardName: 'Rockingham Lodge',
    color: 'orange',
    price: 180,
    rent: 14,
    details1: 'With 1 House $70',
    details2: 'With 2 Houses $200',
    details3: 'With 3 House $550',
    details4: 'With 4 Houses $700',
    details5: 'With 5 Houses $900',
    houseCost: 100,
    mortgage: 90,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Aveling Lodge',
    color: 'orange',
    price: 200,
    rent: 16,
    details1: 'With 1 House $80',
    details2: 'With 2 Houses $220',
    details3: 'With 3 House $600',
    details4: 'With 4 Houses $800',
    details5: 'With 5 Houses $1000',
    houseCost: 100,
    mortgage: 100,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Free Parking',
    clicked: false,
  },
  {
    cardName: 'Brambleberry Lane',
    color: 'red',
    price: 220,
    rent: 18,
    details1: 'With 1 House $90',
    details2: 'With 2 Houses $250',
    details3: 'With 3 House $700',
    details4: 'With 4 Houses $875',
    details5: 'With 5 Houses $1050',
    houseCost: 150,
    mortgage: 110,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chance',
    details1: 'Go to jail. Move directly to jail. Do not pass "GO". Do not collect 200.',
    clicked: false,
  },
  {
    cardName: 'Guildford Lane',
    color: 'red',
    price: 220,
    rent: 18,
    details1: 'With 1 House $90',
    details2: 'With 2 Houses $250',
    details3: 'With 3 House $700',
    details4: 'With 4 Houses $875',
    details5: 'With 5 Houses $1050',
    houseCost: 150,
    mortgage: 110,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Albany Lane',
    color: 'red',
    price: 240,
    rent: 20,
    details1: 'With 1 House $100',
    details2: 'With 2 Houses $300',
    details3: 'With 3 House $750',
    details4: 'With 4 Houses $925',
    details5: 'With 5 Houses $1100',
    houseCost: 150,
    mortgage: 120,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Short Line',
    color: 'railroad',
    price: 200,
    details1: 'If 1 owned $25',
    details2: 'If 2 owned $50',
    details3: 'If 3 owned $100',
    details4: 'If 4 owned $200',
    mortgage: 100,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Elms Villas',
    color: 'yellow',
    price: 260,
    rent: 22,
    details1: 'With 1 House $110',
    details2: 'With 2 Houses $330',
    details3: 'With 3 House $800',
    details4: 'With 4 Houses $975',
    details5: 'With 5 Houses $1150',
    houseCost: 150,
    mortgage: 130,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Keepers Villas',
    color: 'yellow',
    price: 260,
    rent: 22,
    details1: 'With 1 House $110',
    details2: 'With 2 Houses $330',
    details3: 'With 3 House $800',
    details4: 'With 4 Houses $975',
    details5: 'With 5 Houses $1150',
    houseCost: 150,
    mortgage: 130,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Water Works',
    details1: 'If 1 owned, rent equals 4 times dice roll.',
    details2: 'If 2 owned, rent equals 10 times dice roll.',
    mortgage: 75,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Moorcraft Villas',
    color: 'yellow',
    price: 280,
    rent: 24,
    details1: 'With 1 House $120',
    details2: 'With 2 Houses $360',
    details3: 'With 3 House $850',
    details4: 'With 4 Houses $1025',
    details5: 'With 5 Houses $1200',
    houseCost: 150,
    mortgage: 140,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Go to jail',
    clicked: false,
  },
  {
    cardName: 'Whilworth Gardens',
    color: 'green',
    price: 300,
    rent: 26,
    details1: 'With 1 House $130',
    details2: 'With 2 Houses $390',
    details3: 'With 3 House $900',
    details4: 'With 4 Houses $1100',
    details5: 'With 5 Houses $1275',
    houseCost: 200,
    mortgage: 150,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Brock Gardens',
    color: 'green',
    price: 300,
    rent: 26,
    details1: 'With 1 House $130',
    details2: 'With 2 Houses $390',
    details3: 'With 3 House $900',
    details4: 'With 4 Houses $1100',
    details5: 'With 5 Houses $1275',
    houseCost: 200,
    mortgage: 150,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chest',
    details1: 'Bank error in your favor. Collect 200.',
    clicked: false,
  },
  {
    cardName: 'Fair Gardens',
    color: 'green',
    price: 320,
    rent: 28,
    details1: 'With 1 House $150',
    details2: 'With 2 Houses $450',
    details3: 'With 3 House $1000',
    details4: 'With 4 Houses $1200',
    details5: 'With 5 Houses $1400',
    houseCost: 200,
    mortgage: 160,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'B. & O. Railroad',
    color: 'railroad',
    price: 200,
    details1: 'If 1 owned $25',
    details2: 'If 2 owned $50',
    details3: 'If 3 owned $100',
    details4: 'If 4 owned $200',
    mortgage: 100,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chance',
    details1: 'Make general repairs on all your property. For each house pay 25. For each hotel pay 100.',
    clicked: false,
  },
  {
    cardName: 'Hartington Avenue',
    color: 'blue',
    price: 350,
    rent: 35,
    details1: 'With 1 House $175',
    details2: 'With 2 Houses $500',
    details3: 'With 3 House $1100',
    details4: 'With 4 Houses $1300',
    details5: 'With 5 Houses $1500',
    houseCost: 200,
    mortgage: 175,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Luxury Tax',
    clicked: false,
  },
  {
    cardName: 'Meadowlands Avenue',
    color: 'blue',
    price: 400,
    rent: 50,
    details1: 'With 1 House $200',
    details2: 'With 2 Houses $600',
    details3: 'With 3 House $1400',
    details4: 'With 4 Houses $1700',
    details5: 'With 5 Houses $2000',
    houseCost: 200,
    mortgage: 200,
    ownedBy: false,
    clicked: false,
  },
];

export default backOfCards;
